In [1]:
import torch
import torch.nn as nn
# Building your LSTM
# batch_first=True causes input/output tensors to be of shape
# (batch_dim, seq_dim, feature_dim)
# lstm = nn.LSTM(input_dim, hidden_dim, layer_dim, batch_first = True, bidirectional = True)





In [19]:
# in_features: size of each input sample
# out_features: size of each output sample
mlp=nn.Linear(5,10)

In [18]:
mlp??

In [24]:
x=torch.randn(20,10,5)

In [25]:
out=mlp(x)

In [26]:
out.shape

torch.Size([20, 10, 10])

In [30]:
chunk_data=torch.chunk(x,chunks=4,dim=0)

In [34]:
len(chunk_data)

4

In [35]:
chunk_data[0].shape

torch.Size([5, 10, 5])

In [6]:
rnn = nn.LSTM(10, 20, 2,batch_first = False)
print(rnn)
#batch_first = False;(seq_len,batch_size,dim)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

LSTM(10, 20, num_layers=2)


In [3]:
output.shape

torch.Size([5, 3, 20])

In [10]:
'''
input_size – The number of expected features in the input x

hidden_size – The number of features in the hidden state h

num_layers – Number of recurrent layers. E.g., setting num_layers=2 would mean stacking two LSTMs together to form a stacked LSTM, with the second LSTM taking in outputs of the first LSTM and computing the final results. Default: 1
'''
rnn = nn.LSTM(10, 20, 4,batch_first = True)
print(rnn)
#batch_first = True;(batch_size,seq_len,dim)
input = torch.randn( 3,5, 10)
#(layers_size,batch_size,hidden_dim)
h0 = torch.randn(4,3, 20)
c0 = torch.randn(4,3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

LSTM(10, 20, num_layers=4, batch_first=True)


In [11]:
output.shape

torch.Size([3, 5, 20])

In [14]:
rnn = nn.LSTM(10, 20, 4,batch_first = True,bidirectional = True)
print(rnn)
#batch_first = True;(batch_size,seq_len,feature_dim)
input = torch.randn( 3,5, 10)
#(layers_size,batch_size,hidden_dim)
h0 = torch.randn(4,3, 20)
c0 = torch.randn(4,3, 20)
h20=torch.cat([h0,h0],dim = 0)
c20=torch.cat([c0,c0],dim = 0)
output, (hn, cn) = rnn(input, (h20, c20))

LSTM(10, 20, num_layers=4, batch_first=True, bidirectional=True)


In [16]:
#最后一层的两个维度拼接到一起了
output.shape

torch.Size([3, 5, 40])

In [ ]:
'''
LSTM输入: input, (h_0, c_0)

input (seq_len, batch, input_size): 包含输入序列特征的Tensor。也可以是packed variable ，详见 [pack_padded_sequence](#torch.nn.utils.rnn.pack_padded_sequence(input, lengths, batch_first=False[source])

h_0 (num_layers * num_directions, batch, hidden_size):保存着batch中每个元素的初始化隐状态的Tensor

c_0 (num_layers * num_directions, batch, hidden_size): 保存着batch中每个元素的初始化细胞状态的Tensor

LSTM输出 output, (h_n, c_n)

output (seq_len, batch, hidden_size * num_directions): 保存RNN最后一层的输出的Tensor。 如果输入是torch.nn.utils.rnn.PackedSequence，那么输出也是torch.nn.utils.rnn.PackedSequence。

h_n (num_layers * num_directions, batch, hidden_size): Tensor，保存着RNN最后一个时间步的隐状态。

c_n (num_layers * num_directions, batch, hidden_size): Tensor，保存着RNN最后一个时间步的细胞状态。
'''

In [36]:
#expand单个维度进行扩展

In [46]:
x = torch.tensor([1, 2, 3])
x.shape


torch.Size([3])

In [50]:
y=x.expand(2, 3)
y

tensor([[1, 2, 3],
        [1, 2, 3]])

In [51]:
y.shape

torch.Size([2, 3])

In [53]:
y=x.repeat(2,3)
y

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [54]:
y.shape

torch.Size([2, 9])

In [42]:
x = torch.randn(2, 1, 1, 4)
x.shape
x

tensor([[[[ 1.0039,  0.2878, -0.3892,  0.5604]]],


        [[[-0.6791,  0.6856,  0.0732,  0.0825]]]])

In [44]:
x.expand(-1, 2, 3, -1)
# .shape

tensor([[[[ 1.0039,  0.2878, -0.3892,  0.5604],
          [ 1.0039,  0.2878, -0.3892,  0.5604],
          [ 1.0039,  0.2878, -0.3892,  0.5604]],

         [[ 1.0039,  0.2878, -0.3892,  0.5604],
          [ 1.0039,  0.2878, -0.3892,  0.5604],
          [ 1.0039,  0.2878, -0.3892,  0.5604]]],


        [[[-0.6791,  0.6856,  0.0732,  0.0825],
          [-0.6791,  0.6856,  0.0732,  0.0825],
          [-0.6791,  0.6856,  0.0732,  0.0825]],

         [[-0.6791,  0.6856,  0.0732,  0.0825],
          [-0.6791,  0.6856,  0.0732,  0.0825],
          [-0.6791,  0.6856,  0.0732,  0.0825]]]])